import { Main } from "@/components/Main";
import MySwiper from "@/components/MySwiper";
import { Slides } from "@/components/Slides";
import Head from "next/head";

const ITEMS = [
  ["hoge", "huga", "piyo"],
  ["foo", "bar"],
  ["test", "exam", "problem", "confirm"],
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
}
