import { Main } from "@/components/Main";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    document.body.style.backgroundColor = "aliceblue";
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, []);
  return (
    <>
      <Head>
        <title>Happy Birthday dear おっくん</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
}
